behaviors:
  CoinChaser:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 30000
      play_against_latest_model_ratio: 0.5
      window: 10
    keep_checkpoints: 5
    max_steps: 50_000_000
    time_horizon: 128
    summary_freq: 60000
